import { chromium } from "@playwright/test";
import fs from "fs";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const c = await b.newContext({ viewport: { width: 1280, height: 900 } });
await c.addCookies([{ name: "sid", value: fs.readFileSync("/tmp/claude-0/owner.sid", "utf8").trim(), url: "http://localhost:3000" }]);
const p = await c.newPage();
const svc = process.argv[2];
await p.goto(`http://localhost:3000/ru/admin/services/${svc}`, { waitUntil: "networkidle" });
await p.getByRole("button", { name: "Параметры и цены" }).click();
await p.getByRole("button", { name: "Сохранить" }).click();
await p.waitForTimeout(2500);
console.log(await p.locator(".sticky.bottom-0").textContent());
await b.close();
