import { chromium } from "@playwright/test";
const BASE = "http://localhost:3000";
const b = await chromium.launch({ executablePath: "/opt/pw-browsers/chromium" });
const ctx = await b.newContext({ viewport: { width: 390, height: 844 }, deviceScaleFactor: 2, isMobile: true, hasTouch: true, locale: "ru-RU" });
const p = await ctx.newPage();
const errs = [];
p.on("pageerror", (e) => errs.push(e.message));
p.on("console", (m) => m.type() === "error" && errs.push(m.text()));
const shot = (n, full = false) => p.screenshot({ path: `shots/${n}.png`, fullPage: full });

await p.goto(BASE + "/ru/s/regular-cleaning", { waitUntil: "networkidle" });
await p.getByRole("button", { name: /2,5 ч/ }).click();
await p.getByRole("button", { name: /С нашими материалами/ }).click();
await p.getByRole("button", { name: /Каждую неделю/ }).click();
await shot("01-service");
await p.getByRole("button", { name: "Продолжить" }).click();
await p.waitForURL(/\/book\//);
await p.waitForLoadState("networkidle");
await shot("02-login");
await p.locator("#phone").fill("+374 91 000001");
await p.getByRole("button", { name: /WhatsApp/ }).click();
await p.getByText(/Тестовый режим/).waitFor();
const code = (await p.getByText(/Тестовый режим/).textContent()).match(/(\d{4,6})/)[1];
await shot("03-code");
await p.locator("#code").fill(code);
await p.waitForTimeout(2500); await shot("03b-after");
await p.locator("#name").waitFor();
await p.locator("#name").fill("Артур");
await p.getByRole("button", { name: "Продолжить" }).click();
await p.getByRole("button", { name: /Новый адрес/ }).waitFor();
await p.getByRole("button", { name: /Новый адрес/ }).click();
await p.locator("select").selectOption("Кентрон");
await p.locator("form input").nth(0).fill("Туманяна");
await p.locator("form input").nth(1).fill("12");
await p.locator("form input").nth(2).fill("34");
await shot("04-address");
await p.getByRole("button", { name: "Сохранить адрес" }).click();
await p.waitForTimeout(800);
await p.locator(".grid-cols-4 button").first().waitFor();
await p.locator(".grid-cols-4 button").nth(2).click();
await p.waitForTimeout(300);
await shot("05-checkout", true);
await p.getByRole("button", { name: "Подтвердить заказ" }).click();
await p.waitForURL(/\/account\/orders\//, { timeout: 20000 });
await p.waitForLoadState("networkidle");
await shot("06-order", true);
const cookies = await ctx.cookies();
console.log("SID", cookies.find((c) => c.name === "sid")?.value);
console.log("ERRORS", errs);
await b.close();
